# Generated by Django 4.1.4 on 2022-12-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0014_checklistanswer_urbanland_requestid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestDB',
            new_name='Request',
        ),
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
    ]
