# Generated by Django 4.1.4 on 2022-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0016_request_requestdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPartnerManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'fieldpartnermanager',
            },
        ),
    ]
