# Generated by Django 4.1.4 on 2022-12-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0017_fieldpartnermanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('ownername', models.CharField(max_length=100, null=True)),
                ('kathanumber', models.CharField(max_length=100, null=True)),
                ('dharinipassbooknumber', models.CharField(max_length=100, null=True)),
                ('aadharnumber', models.CharField(max_length=4, null=True)),
                ('ownserssowodoname', models.CharField(max_length=100, null=True)),
                ('ownermobilenumber', models.CharField(max_length=15, null=True)),
                ('ownermobilestatus', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'propertyowner',
            },
        ),
    ]
