# Generated by Django 4.1.4 on 2022-12-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0018_propertyowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('paymentdate', models.DateTimeField(null=True)),
                ('paymentmode', models.CharField(max_length=40, null=True)),
                ('paymentreference', models.CharField(max_length=100, null=True)),
                ('amountpaid', models.DecimalField(decimal_places=2, max_digits=13)),
                ('status', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'requestpayment',
            },
        ),
    ]
