# Generated by Django 4.1.4 on 2022-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0019_requestpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='owneremail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestcode',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
