# Generated by Django 4.1.4 on 2022-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0020_propertyowner_owneremail_request_requestcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('requestpropertyid', models.IntegerField()),
                ('surveyslno', models.IntegerField()),
                ('surveyvillagename', models.CharField(max_length=100, null=True)),
                ('surveynubmber', models.CharField(max_length=40, null=True)),
                ('surveyextent', models.DecimalField(decimal_places=3, max_digits=13)),
                ('units', models.CharField(max_length=40, null=True)),
                ('natureofland', models.CharField(max_length=100, null=True)),
                ('classifcationofland', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'propertysurvey',
            },
        ),
        migrations.CreateModel(
            name='RequestSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('scheduledt1', models.DateTimeField(null=True)),
                ('scheduletime1', models.CharField(max_length=15, null=True)),
                ('scheduledt2', models.DateTimeField(null=True)),
                ('scheduletime2', models.CharField(max_length=15, null=True)),
                ('scheduledt3', models.DateTimeField(null=True)),
                ('scheduletime3', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'requestschedule',
            },
        ),
    ]
